### ISSUE TITLE
lastmod not displaying correctly

### ISSUE THREAD

**Issue by imizwa** [gocom/rah_sitemap#10]
Hi Jukka, so I had an outdated version of rah_sitemap and had the lastmod issue. I completely removed it and install version 4.0 a few months back and it was working fine. I went to check Google Webmasters and it's telling me the lastmod error is happening again. I checked it and it is displaying just a single number:

https://www.ricmedia.com/?rah_sitemap=sitemap.article.1

just wondering if my server timestamp may be an issue or something else?

thanks in advance. Rich Brereton

**Comment by gocom** [comment]
@imizwa Could very likely be a server issue, or something in how Textpattern CMS handles it's date formatting.

rah_sitemap itself doesn't do anything else than calls Textpattern's safe_strftime, which is supposed to be calling PHP's date function. It's given `c` as a timestamp, which will return a ISO-8601 formatted date.

What is your:

1. OS and version?
2. PHP version and how it is installed?
3. Texptattern CMS version

**Comment by gocom** [comment]
You can also try the current development build, which replaces the `c` format string with more explicit formatting string.

You can download plugin installation files from CI build results, the Artifacts section at the end:
https://github.com/gocom/rah_sitemap/actions/runs/4185770253

**Comment by imizwa** [comment]
Hi Jukka, thanks for getting back to me. The dev version is working but it does leave a \ backslash at the end of the date but that shouldn't be an issue.

https://www.ricmedia.com/?rah_sitemap=sitemap.article.1

I am with Dreamhost VPS running PHP 8.1 FastCGI on Ubuntu (I presume 22.04 but they don't give much detail). Textpattern is 4.8.8.

Thanks again.

**Comment by gocom** [comment]
@imizwa Those dates appears all wonky. That is likely caused by Textpattern core issue, where it ends up doing something nasty with the date time string. Textpattern's `safe_strftime`  code is all wonky, and it ends up generating dates with one of 5 different PHP date functions based on host system, or even position of the moon.

I'll likely have to implement my own to get some form of consistent date formatting. Thankfully doing so is no longer that much of a issue; at some point timezones were coupled to the `safe_strftime`, but it doesn't seem to be no longer.

**Comment by gocom** [comment]
@imizwa I now swapped away from Textpattern's safe_strftime() to intended date function in the latest development version. This should hopefully fix the issues you were having, if they were caused by safe_strftime being 'random'.

You can download plugin installation files from CI build results, the Artifacts section at the end:
https://github.com/gocom/rah_sitemap/actions/runs/4207448348

**Comment by imizwa** [comment]
Hi Jukka, yep that seems to have fixed the issue. Date is now displaying in the proper format.

https://www.ricmedia.com/?rah_sitemap=sitemap.article.1

Thanks so much Jukka, really appreciate your work.
