### ISSUE TITLE
If Textpattern has many articles, sitemap not generated

### ISSUE THREAD

**Issue by kuopassa** [gocom/rah_sitemap#7]
I have a Textpattern installation with more than 170k articles. I'm trying to include published articles to the sitemap output, but the output is this:

`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes) in textpattern\lib\txplib_db.php on line 437`

**Comment by gocom** [comment]
Current development version should now handle almost unlimited number of articles. Instead of the plugin generating single huge sitemap, it generates an index which links to number of smaller split sitemaps, which each containing up-to 50,000 articles each.

![Screenshot 2022-04-22 at 22 33 49](https://user-images.githubusercontent.com/665186/164782510-232e09b4-ca50-4a82-b2e3-b7d46fee928d.png)

This development version's plugin packages can be downloaded from CI artifacts:
https://github.com/gocom/rah_sitemap/actions/runs/2209668535
